version: '3.8'

services:
  airflow-webserver:
    image: apache/airflow:2.8.0-python3.11
    container_name: airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://openly_user:openly_password@openly_db:5432/openly_db
      - AIRFLOW__CORE__FERNET_KEY=81HqDtbqAywKSOumSha3BhWNOdQ26slT6K0YaZeZyPs=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
    ports:
      - "8084:8080"
    volumes:
      - /mnt/bigdata/airflow/dags:/opt/airflow/dags
      - /mnt/bigdata/airflow/logs:/opt/airflow/logs
      - /mnt/bigdata/airflow/plugins:/opt/airflow/plugins
    command: webserver
    networks:
      - smart-city-network
    depends_on:
      - airflow-init

  airflow-scheduler:
    image: apache/airflow:2.8.0-python3.11
    container_name: airflow-scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://openly_user:openly_password@openly_db:5432/openly_db
      - AIRFLOW__CORE__FERNET_KEY=81HqDtbqAywKSOumSha3BhWNOdQ26slT6K0YaZeZyPs=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - /mnt/bigdata/airflow/dags:/opt/airflow/dags
      - /mnt/bigdata/airflow/logs:/opt/airflow/logs
      - /mnt/bigdata/airflow/plugins:/opt/airflow/plugins
    command: scheduler
    networks:
      - smart-city-network
    depends_on:
      - airflow-init

  airflow-init:
    image: apache/airflow:2.8.0-python3.11
    container_name: airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://openly_user:openly_password@openly_db:5432/openly_db
      - AIRFLOW__CORE__FERNET_KEY=81HqDtbqAywKSOumSha3BhWNOdQ26slT6K0YaZeZyPs=
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
    volumes:
      - /mnt/bigdata/airflow/dags:/opt/airflow/dags
      - /mnt/bigdata/airflow/logs:/opt/airflow/logs
      - /mnt/bigdata/airflow/plugins:/opt/airflow/plugins
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true
    networks:
      - smart-city-network

networks:
  smart-city-network:
    external: true

