version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /mnt/bigdata/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /mnt/bigdata/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - smart-city-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - /mnt/bigdata/grafana/data:/var/lib/grafana
    networks:
      - smart-city-network
    depends_on:
      - prometheus

networks:
  smart-city-network:
    external: true

