version: '3.8'

services:
  jobmanager:
    image: flink:1.18.1-scala_2.12-java11
    container_name: flink-jobmanager
    ports:
      - "8082:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
        parallelism.default: 2
    volumes:
      - /mnt/bigdata/flink-data/checkpoints:/tmp/flink-checkpoints
      - /mnt/bigdata/flink-data/savepoints:/tmp/flink-savepoints
    networks:
      - smart-city-network

  taskmanager:
    image: flink:1.18.1-scala_2.12-java11
    container_name: flink-taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
        taskmanager.memory.process.size: 2048m
    volumes:
      - /mnt/bigdata/flink-data/checkpoints:/tmp/flink-checkpoints
      - /mnt/bigdata/flink-data/savepoints:/tmp/flink-savepoints
    networks:
      - smart-city-network

networks:
  smart-city-network:
    external: true

