version: '3.8'

services:
  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8083:8080"
      - "7077:7077"
    environment:
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - /mnt/bigdata/spark-data:/opt/spark-data
      - /mnt/bigdata/spark-apps:/opt/spark-apps
    networks:
      - smart-city-network

  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - /mnt/bigdata/spark-data:/opt/spark-data
      - /mnt/bigdata/spark-apps:/opt/spark-apps
    networks:
      - smart-city-network

networks:
  smart-city-network:
    external: true

